Repository IBMStreams/streamsx.topology, pull requests merged in 2018-02, with the labels that each got.

#1459 Support streamsx.ec and tester with Python 2.7
  com.ibm.streamsx.topology/opt/python/include/splpy_ec.h
  com.ibm.streamsx.topology/opt/python/include/splpy_ec_api.h
  com.ibm.streamsx.topology/opt/python/include/splpy_setup.h
  com.ibm.streamsx.topology/opt/python/include/splpy_sym.h
  com.ibm.streamsx.topology/opt/python/packages/streamsx/_streams/_placement.py
  com.ibm.streamsx.topology/opt/python/packages/streamsx/ec.py
  com.ibm.streamsx.topology/opt/python/packages/streamsx/rest.py
  com.ibm.streamsx.topology/opt/python/packages/streamsx/rest_primitives.py
  com.ibm.streamsx.topology/opt/python/packages/streamsx/scripts/extract.py
  com.ibm.streamsx.topology/opt/python/packages/streamsx/scripts/runner.py
  com.ibm.streamsx.topology/opt/python/packages/streamsx/spl/op.py
  com.ibm.streamsx.topology/opt/python/packages/streamsx/spl/runtime.py
  com.ibm.streamsx.topology/opt/python/packages/streamsx/spl/spl.py
  com.ibm.streamsx.topology/opt/python/packages/streamsx/spl/toolkit.py
  com.ibm.streamsx.topology/opt/python/packages/streamsx/spl/types.py
  com.ibm.streamsx.topology/opt/python/packages/streamsx/st.py
  com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/context.py
  com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/dependency.py
  com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/exop.py
  com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/functions.py
  com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/graph.py
  com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/mqtt.py
  com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/param.py
  com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/runtime.py
  com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/schema.py
  com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/tester.py
  com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/tester_runtime.py
  com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/topology.py
  test/python/rest/test_rest_bluemix.py
  test/python/rest/test_vers.py
  test/python/topology/test2.py
  test/python/topology/test2_python_window.py
  test/python/topology/test_functions.py
  test/python/topology/test_schemas.py
  test/python/topology/test_vers.py
Labels: 1.9, enhancement, python_app_api

#1474 Correct url for retrieving build logs.
  java/src/com/ibm/streamsx/rest/StreamingAnalyticsServiceV2.java
Labels: backport_v1_8

#1482 Test passes under v2 WAMS service
  test/python/topology/test2_job_config.py
Labels: backport_v1_8

#1464 Create PortProperties interface, and add setParallel to TStream.
  java/src/com/ibm/streamsx/topology/TStream.java
  java/src/com/ibm/streamsx/topology/builder/BOutput.java
  java/src/com/ibm/streamsx/topology/builder/GraphBuilder.java
  java/src/com/ibm/streamsx/topology/generator/operator/OpProperties.java
  java/src/com/ibm/streamsx/topology/generator/port/PortProperties.java
  java/src/com/ibm/streamsx/topology/internal/core/StreamImpl.java
  java/src/com/ibm/streamsx/topology/spl/SPLStream.java
  java/src/com/ibm/streamsx/topology/spl/SPLStreamImpl.java
Labels: 1.9

#1475 Fix #1471 - Add remote build submission metrics such as upload time
  java/src/com/ibm/streamsx/rest/AbstractStreamingAnalyticsService.java
  java/src/com/ibm/streamsx/topology/internal/context/remote/SubmissionResultsKeys.java
  test/python/topology/test2_submission_result.py
Labels: 1.9, java_rest_api

#1484 Fix #1483 - Remove --rebuild-toolkits
  com.ibm.streamsx.topology/opt/client/remote/Makefile.template
Labels: backport_v1_8

#1493 Fix Initializable protocol when running with checkpointing
  java/execute/src/com/ibm/streamsx/topology/internal/functional/FunctionalHandler.java
  java/execute/src/com/ibm/streamsx/topology/internal/functional/StatelessFunctionalHandler.java
  java/execute/src/com/ibm/streamsx/topology/internal/functional/ops/FunctionOperatorContext.java
  java/execute/src/com/ibm/streamsx/topology/internal/functional/ops/FunctionalOpUtils.java
  java/execute/src/com/ibm/streamsx/topology/internal/functional/ops/StatefulFunctionalHandler.java
  java/runtime/src/com/ibm/streamsx/topology/function/Initializable.java
  test/java/src/com/ibm/streamsx/topology/test/state/CheckpointTest.java
  test/java/src/com/ibm/streamsx/topology/test/state/StatefulApp.java
Labels: backport_v1_8

#1496 Use V1/Basic when given a mixed credentials object
  com.ibm.streamsx.topology/opt/python/packages/streamsx/rest_primitives.py
Labels: backport_v1_8
