Repository IBMStreams/streamsx.topology, pull requests merged in 2020-05, with the labels that each got.

#2426 Feature/filter dropped
  com.ibm.streamsx.topology/com.ibm.streamsx.topology.functional.python/Filter/Filter.xml
  com.ibm.streamsx.topology/com.ibm.streamsx.topology.functional.python/Filter/Filter_cpp.cgt
  com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/topology.py
  java/src/com/ibm/streamsx/topology/generator/spl/Optimizer.java
  test/python/topology/test2_filter.py
Labels: 1.15, enhancement, python_topology

#2428 Feature/parallel Routing.KEY_PARTITIONED
  com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/topology.py
  test/python/topology/test2_parallel_key_partitioned.py
Labels: 1.15, enhancement, python_topology

#2441 fix typo in documentation, note added for __exit__
  com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/topology.py
Labels: 1.15, doc

#2431 Submit Python applications in Java 8 to Java 11 environments
  com.ibm.streamsx.topology/opt/jaxb/jakarta.activation-1.2.2.jar
  com.ibm.streamsx.topology/opt/jaxb/jaxb-api-2.3.1.jar
  com.ibm.streamsx.topology/opt/jaxb/jaxb-impl-2.3.3.jar
  common-build.xml
Labels: 1.15, enhancement, java_rest_api

#2445 1.15.0.alpha
  com.ibm.streamsx.topology/info.xml
  com.ibm.streamsx.topology/opt/python/packages/streamsx/_streams/_version.py
Labels: 1.15

#2455 Feature/edge
  com.ibm.streamsx.topology/opt/python/packages/streamsx/rest_primitives.py
  com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/context.py
  com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/context.pyi
  java/src/com/ibm/streamsx/rest/build/Artifact.java
  java/src/com/ibm/streamsx/rest/build/BaseImage.java
  java/src/com/ibm/streamsx/rest/build/Build.java
  java/src/com/ibm/streamsx/rest/build/BuildPool.java
  java/src/com/ibm/streamsx/rest/build/BuildService.java
  java/src/com/ibm/streamsx/rest/build/StreamsBuildService.java
  java/src/com/ibm/streamsx/rest/internal/BuildType.java
  java/src/com/ibm/streamsx/rest/internal/ICP4DAuthenticator.java
  java/src/com/ibm/streamsx/topology/context/StreamsContext.java
  java/src/com/ibm/streamsx/topology/context/StreamsContextFactory.java
  java/src/com/ibm/streamsx/topology/context/remote/RemoteContext.java
  java/src/com/ibm/streamsx/topology/context/remote/RemoteContextFactory.java
  java/src/com/ibm/streamsx/topology/internal/context/remote/DeployKeys.java
  java/src/com/ibm/streamsx/topology/internal/context/remote/SubmissionResultsKeys.java
  java/src/com/ibm/streamsx/topology/internal/context/remote/ZippedToolkitRemoteContext.java
  java/src/com/ibm/streamsx/topology/internal/context/streams/RemoteEdgeContext.java
  java/src/com/ibm/streamsx/topology/internal/context/streamsrest/BuildServiceContext.java
  java/src/com/ibm/streamsx/topology/internal/context/streamsrest/BuildServiceSetters.java
  java/src/com/ibm/streamsx/topology/internal/context/streamsrest/EdgeImageContext.java
  test/python/topology/test2_edge.py
Labels: 1.15, enhancement

#2469 1.15.0.beta
  com.ibm.streamsx.topology/info.xml
  com.ibm.streamsx.topology/opt/python/packages/streamsx/_streams/_version.py
Labels: 1.15

#2470 Avoid buffering the entire HTTP entity in memory when downloading the SAB
  java/src/com/ibm/streamsx/rest/build/StreamsRestUtils.java
  java/src/com/ibm/streamsx/rest/internal/InputStreamConsumer.java
Labels: 1.15
